import { useMemo, useState } from 'react'
import { Check, ChevronRight, Clock3, HeartPulse, ImagePlus, Medal, ShieldCheck, SlidersHorizontal, Target, Trophy, Users } from 'lucide-react'
import { Button } from '../../ui/Button'
import { EmptyState } from '../../ui/EmptyState'
import { ErrorState } from '../../ui/ErrorState'
import { Sheet } from '../../ui/Sheet'
import { Skeleton } from '../../ui/Skeleton'
import { MomentumCard } from './RepMomentum'
import { BOARD_ROWS, TEAM_GAME_CONFIG, WELLBEING_FLAGS } from './momentumMocks'
import type { ScoreSourceKeyPreview, SprintCadencePreview, VisibilityModePreview } from './momentumMocks'

const SOURCE_LABEL: Record<ScoreSourceKeyPreview, string> = { behaviors: 'Behaviors', outcomes: 'Outcomes', improvement: 'Improvement', team_goal: 'Team goal' }
const VISIBILITY_COPY: Record<VisibilityModePreview, string> = {
  full_board: 'Reps see the full board, but Today shows only their next rung.',
  top_three: 'Reps see the top three and their own personal-best framing.',
  private: 'Reps see only their own baseline, progress and achievements.',
}

function ConfigButton<T extends string>({ value, current, label, onSelect }: { value: T; current: T; label: string; onSelect: (value: T) => void }) {
  return <button onClick={() => onSelect(value)} aria-pressed={current === value} className={['min-h-10 rounded-md border px-3 text-xs font-semibold', current === value ? 'border-accent bg-accent-subtle text-accent' : 'border-border bg-surface text-fg-muted hover:border-border-strong'].join(' ')}>{label}</button>
}

function ChallengeComposer({ visibility }: { visibility: VisibilityModePreview }) {
  const [template, setTemplate] = useState<'most_x' | 'first_to_n' | 'team_total' | 'beat_own_best'>('beat_own_best')
  const [metric, setMetric] = useState('follow_ups')
  const [participants, setParticipants] = useState<'team' | 'subset'>('team')
  const [prize, setPrize] = useState(false)
  const [preview, setPreview] = useState(false)
  const [launched, setLaunched] = useState(false)
  const templates = [
    ['most_x', 'Most X this sprint'], ['first_to_n', 'First to N'], ['team_total', 'Team total reaches Y'], ['beat_own_best', 'Beat your own best'],
  ] as const
  return <div className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]"><section className="rounded-xl border border-border bg-surface p-4 shadow-elev-1"><p className="label-caps text-accent">Challenge composer · Preview</p><h3 className="mt-1 text-lg font-semibold tracking-[-0.025em] text-fg">Make the goal worth repeating.</h3><p className="mt-1 text-xs text-fg-muted">Prefer team and personal-best templates when the group needs energy without pressure.</p>
    <div className="mt-5"><label className="text-xs font-semibold text-fg">Template</label><div className="mt-2 grid grid-cols-2 gap-2">{templates.map(([key, label]) => <ConfigButton key={key} value={key} current={template} label={label} onSelect={setTemplate} />)}</div></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-fg">Metric<select value={metric} onChange={(event) => setMetric(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-border bg-surface-raised px-3 text-xs text-fg"><option value="follow_ups">On-time follow-ups</option><option value="bookings">Bookings</option><option value="calls">Calls logged</option><option value="revenue">Revenue</option><option value="objections_logged">Objections logged</option></select></label><label className="text-xs font-semibold text-fg">Duration<select className="mt-2 h-10 w-full rounded-md border border-border bg-surface-raised px-3 text-xs text-fg" defaultValue="7"><option value="3">3 workdays</option><option value="7">7 days</option><option value="14">One sprint</option></select></label></div>
    <div className="mt-4"><p className="text-xs font-semibold text-fg">Participants</p><div className="mt-2 grid grid-cols-2 gap-2"><ConfigButton value="team" current={participants} label="Whole team" onSelect={setParticipants} /><ConfigButton value="subset" current={participants} label="Choose subset" onSelect={setParticipants} /></div>{participants === 'subset' && <div className="mt-2 flex flex-wrap gap-1.5">{['Asha', 'Priya', 'Nikhil', 'Rahul'].map((name, index) => <button key={name} aria-pressed={index < 3} className={['rounded-pill border px-2.5 py-1.5 text-2xs font-semibold', index < 3 ? 'border-accent bg-accent-subtle text-accent' : 'border-border text-fg-muted'].join(' ')}>{name}</button>)}</div>}</div>
    <div className="mt-4 rounded-xl border border-dashed border-border-strong p-3"><button onClick={() => setPrize((value) => !value)} className="flex w-full items-center gap-3 text-left"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-surface-sunk text-fg-muted"><ImagePlus aria-hidden size={17} /></span><span className="min-w-0 flex-1"><strong className="block text-xs text-fg">Optional prize card</strong><span className="mt-0.5 block text-2xs text-fg-muted">Photo upload, title and caption</span></span><span className="text-2xs font-semibold text-accent">{prize ? 'Remove' : 'Attach'}</span></button>{prize && <div className="mt-3 grid grid-cols-[96px_1fr] gap-3 border-t border-border pt-3"><div role="img" aria-label="Sample uploaded team lunch photo" className="min-h-20 rounded-lg bg-[linear-gradient(145deg,#d6b989,#6d876f)]" /><div className="space-y-2"><input defaultValue="Team lunch" aria-label="Prize title" className="h-9 w-full rounded-md border border-border bg-surface-raised px-3 text-xs text-fg" /><input defaultValue="A long-table lunch together." aria-label="Prize caption" className="h-9 w-full rounded-md border border-border bg-surface-raised px-3 text-xs text-fg" /></div></div>}</div>
    <div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => setPreview((value) => !value)} variant="secondary">Preview as rep</Button><Button onClick={() => setLaunched(true)}>Review launch</Button></div>{launched && <p className="mt-3 flex items-center gap-1.5 text-xs font-semibold text-success" role="status"><Check aria-hidden size={13} />Challenge ready in preview—nothing was launched.</p>}
  </section>
  <aside className="rounded-xl border border-border bg-surface-sunk p-4"><p className="label-caps">Rep preview · {visibility.replaceAll('_', ' ')}</p><article className="mt-3 overflow-hidden rounded-xl border border-border bg-surface shadow-elev-2"><div className="p-4"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent-subtle text-accent"><Target aria-hidden size={18} /></span><h3 className="mt-3 text-md font-semibold text-fg">{template === 'beat_own_best' ? 'A cleaner follow-up week' : templates.find(([key]) => key === template)?.[1]}</h3><p className="mt-1 text-xs text-fg-muted">{metric.replaceAll('_', ' ')} · {participants === 'team' ? 'whole team' : 'selected reps'}</p><div className="mt-4 flex items-end justify-between"><span><strong className="tnum text-xl text-fg">24</strong><span className="text-xs text-fg-muted"> / 32</span></span><span className="text-2xs font-semibold text-success">{visibility === 'private' ? '8 from your target' : visibility === 'top_three' ? 'Top pace: 27' : 'Leader: 27'}</span></div><div className="mt-2 h-2 overflow-hidden rounded-pill bg-surface-sunk"><div className="h-full w-3/4 rounded-pill bg-accent" /></div><p className="mt-3 text-2xs text-fg-muted">6 workdays left · no after-hours countdown</p></div>{prize && <div className="grid grid-cols-[82px_1fr] border-t border-border bg-surface-sunk"><div className="bg-[linear-gradient(145deg,#d6b989,#6d876f)]" /><div className="p-3"><p className="label-caps">Prize</p><p className="mt-1 text-xs font-semibold text-fg">Team lunch</p></div></div>}</article>{preview && <p className="mt-3 rounded-lg bg-success-subtle p-3 text-xs text-success">Preview active. This is exactly the comparison level reps receive.</p>}</aside></div>
}

function CompetitionBoard() {
  const [league, setLeague] = useState<'main' | 'improvement'>('main')
  const [selected, setSelected] = useState<(typeof BOARD_ROWS)[number] | null>(null)
  const rows = useMemo(() => league === 'main' ? BOARD_ROWS : [...BOARD_ROWS].sort((a, b) => b.improvementPct - a.improvementPct), [league])
  return <><section className="overflow-hidden rounded-xl border border-border bg-surface shadow-elev-1"><header className="flex flex-wrap items-end justify-between gap-3 border-b border-border p-4"><div><p className="label-caps text-accent">Full board · Manager only · Preview</p><h3 className="mt-1 text-lg font-semibold text-fg">Recognition without a red zone.</h3><p className="mt-1 text-xs text-fg-muted">Bottom-half rows use personal progress framing; nobody is labelled last or declining.</p></div><select aria-label="Board sprint" className="h-10 rounded-md border border-border bg-surface-raised px-3 text-xs text-fg"><option>1–14 August</option><option>15–31 July</option><option>1–14 July</option></select></header><div className="flex gap-1 border-b border-border bg-surface-sunk p-2" role="tablist" aria-label="Competition league"><button role="tab" aria-selected={league === 'main'} onClick={() => setLeague('main')} className={['rounded-md px-3 py-2 text-xs font-semibold', league === 'main' ? 'bg-surface text-fg shadow-elev-1' : 'text-fg-muted'].join(' ')}>Main</button><button role="tab" aria-selected={league === 'improvement'} onClick={() => setLeague('improvement')} className={['rounded-md px-3 py-2 text-xs font-semibold', league === 'improvement' ? 'bg-surface text-fg shadow-elev-1' : 'text-fg-muted'].join(' ')}>Improvement · vs own baseline</button></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-xs"><thead><tr className="border-b border-border text-fg-subtle"><th className="px-4 py-3 text-left font-semibold">Position</th><th className="px-4 py-3 text-left font-semibold">Rep</th><th className="px-4 py-3 text-right font-semibold">{league === 'main' ? 'Points' : 'Improvement'}</th><th className="px-4 py-3 text-right font-semibold">Revenue</th><th className="px-4 py-3 text-left font-semibold">Healthy framing</th><th className="px-4 py-3" /></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id} className="border-b border-border last:border-0"><td className="tnum px-4 py-3 text-fg-muted">#{index + 1}</td><td className="px-4 py-3 font-semibold text-fg">{row.name}</td><td className="tnum px-4 py-3 text-right font-semibold text-fg">{league === 'main' ? row.points.toLocaleString('en-IN') : `+${row.improvementPct}%`}</td><td className="tnum px-4 py-3 text-right text-fg-muted">₹{(row.revenue / 100000).toFixed(1)}L</td><td className="px-4 py-3 text-fg-muted">{row.framing}</td><td className="px-4 py-3 text-right"><button onClick={() => setSelected(row)} className="inline-flex min-h-8 items-center gap-1 rounded-md px-2 text-2xs font-semibold text-accent hover:bg-accent-subtle">Drill in <ChevronRight aria-hidden size={12} /></button></td></tr>)}</tbody></table></div></section>
    <section className="mt-4 rounded-xl border border-border bg-surface p-4 shadow-elev-1"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-success-subtle text-success"><Medal aria-hidden size={18} /></span><div><p className="label-caps text-success">Rookie ramp · Never ranked</p><h3 className="mt-1 text-sm font-semibold text-fg">First 30 days are a milestone track.</h3></div></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{['Leena · day 12', 'Arjun · day 23'].map((rep, repIndex) => <article key={rep} className="rounded-xl border border-border bg-surface-sunk p-3"><p className="text-xs font-semibold text-fg">{rep}</p><div className="mt-3 grid grid-cols-4 gap-2">{['First call', 'First booking', 'First close', 'First ₹1L'].map((step, index) => <div key={step} className="text-center"><span className={['mx-auto flex h-8 w-8 items-center justify-center rounded-pill border', index < 2 + repIndex ? 'border-success bg-success-subtle text-success' : 'border-border bg-surface text-fg-subtle'].join(' ')}>{index < 2 + repIndex ? <Check aria-hidden size={13} /> : index + 1}</span><p className="mt-1 text-2xs leading-tight text-fg-muted">{step}</p></div>)}</div></article>)}</div></section>
    <Sheet open={!!selected} onClose={() => setSelected(null)} title={selected ? `${selected.name} · score composition` : 'Score composition'}>{selected && <div><div className="rounded-xl bg-surface-sunk p-4"><p className="label-caps">Sprint read · Preview</p><div className="mt-2 flex items-end justify-between"><strong className="tnum text-3xl text-fg">{selected.points.toLocaleString('en-IN')}</strong><span className="text-xs font-semibold text-success">+{selected.improvementPct}% vs own baseline</span></div><p className="mt-2 text-xs text-fg-muted">{selected.framing}. No public decline indicator is produced.</p></div><div className="mt-5 space-y-3">{[['Behaviors', 40, 514], ['Outcomes', 35, 450], ['Improvement', 15, 193], ['Team goal', 10, 128]].map(([label, weight, points]) => <div key={String(label)}><div className="flex items-center justify-between text-xs"><span className="font-semibold text-fg">{label} · {weight}%</span><span className="tnum text-fg-muted">{points}</span></div><div className="mt-1.5 h-2 rounded-pill bg-surface-sunk"><div className="h-full rounded-pill bg-accent" style={{ width: `${Number(weight) * 1.8}%` }} /></div></div>)}</div><svg viewBox="0 0 300 90" className="mt-5 w-full" role="img" aria-label="Score trend rising over six days"><polyline points="10,72 65,66 120,51 175,56 230,35 290,24" fill="none" stroke="var(--accent)" strokeWidth="3" strokeLinecap="round" /></svg><p className="text-2xs text-fg-subtle">Preview — manager drill-in is not wired.</p></div>}</Sheet>
  </>
}

function BurnoutPanel() {
  const [acted, setActed] = useState<Record<string, boolean>>({})
  return <div className="grid gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]"><section className="overflow-hidden rounded-xl border border-border bg-surface shadow-elev-1"><header className="flex items-start gap-3 border-b border-border p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-info-subtle text-info"><HeartPulse aria-hidden size={18} /></span><div><p className="label-caps text-info">Care signals · Manager only · Preview</p><h3 className="mt-1 text-lg font-semibold text-fg">Notice strain before it becomes a number.</h3><p className="mt-1 text-xs text-fg-muted">These are prompts for a supportive conversation—not performance evidence.</p></div></header><div className="divide-y divide-border">{WELLBEING_FLAGS.map((flag) => <article key={flag.id} className="p-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-fg">{flag.rep}</p><p className="mt-1 text-xs leading-relaxed text-fg-muted">{flag.context}</p></div><button onClick={() => setActed((value) => ({ ...value, [flag.id]: true }))} className={['min-h-9 rounded-pill border px-3 text-2xs font-semibold', acted[flag.id] ? 'border-success/25 bg-success-subtle text-success' : 'border-border bg-surface text-fg-muted hover:border-accent hover:text-accent'].join(' ')}>{acted[flag.id] ? 'Noted privately' : flag.suggestedAction}</button></div></article>)}</div></section><aside className="rounded-xl border border-border bg-surface p-4 shadow-elev-1"><p className="label-caps text-accent">Anonymous team mood</p><h3 className="mt-1 text-md font-semibold text-fg">Steadier after a heavy week.</h3><p className="mt-1 text-xs leading-relaxed text-fg-muted">Aggregate only · 8 of 9 optional responses · no individual answer is available.</p><svg viewBox="0 0 320 160" className="mt-4 w-full" role="img" aria-label="Aggregate team mood trend improving slightly over six weeks"><defs><linearGradient id="mood-area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--info)" stopOpacity=".22" /><stop offset="1" stopColor="var(--info)" stopOpacity="0" /></linearGradient></defs><path d="M10 118 L65 92 L120 105 L175 78 L230 72 L305 48 L305 145 L10 145 Z" fill="url(#mood-area)" /><polyline points="10,118 65,92 120,105 175,78 230,72 305,48" fill="none" stroke="var(--info)" strokeWidth="3" strokeLinecap="round" /><line x1="10" y1="130" x2="305" y2="130" stroke="var(--border)" /></svg><div className="mt-3 rounded-lg bg-info-subtle p-3 text-xs text-info"><strong>Suggested manager action:</strong> protect Friday’s quiet hours and keep Monday planning light.</div></aside></div>
}

export default function CompetitionConsole({ previewState = 'ready' }: { previewState?: 'ready' | 'loading' | 'empty' | 'error' }) {
  const [tab, setTab] = useState<'rules' | 'challenge' | 'board' | 'care'>('rules')
  const [visibility, setVisibility] = useState<VisibilityModePreview>(TEAM_GAME_CONFIG.visibility)
  const [sprint, setSprint] = useState<SprintCadencePreview>(TEAM_GAME_CONFIG.sprint)
  const [weights, setWeights] = useState(TEAM_GAME_CONFIG.weights)
  const [quietPreview, setQuietPreview] = useState(false)
  const [start, setStart] = useState(TEAM_GAME_CONFIG.quietHours.workdayStart)
  const [end, setEnd] = useState(TEAM_GAME_CONFIG.quietHours.workdayEnd)

  if (previewState === 'loading') return <Skeleton className="h-[520px]" />
  if (previewState === 'empty') return <EmptyState icon={Trophy} title="Momentum is off for this team." body="Choose a visibility mode and scoring policy before reps see any competition surface." />
  if (previewState === 'error') return <ErrorState title="Couldn’t load Momentum settings" body="The last saved policy remains in force. Try again before publishing changes." onRetry={() => undefined} />

  const updateWeight = (key: ScoreSourceKeyPreview, next: number) => {
    const clamped = Math.max(5, Math.min(70, Math.round(next)))
    const draft = { ...weights }
    const delta = clamped - draft[key]
    if (delta === 0) return
    const others = (Object.keys(draft) as ScoreSourceKeyPreview[]).filter((item) => item !== key).sort((a, b) => draft[b] - draft[a])
    if (delta > 0) {
      let remaining = delta
      for (const item of others) { const available = draft[item] - 5; const take = Math.min(available, remaining); draft[item] -= take; remaining -= take }
      if (remaining > 0) return
    } else draft[others[0]] += -delta
    draft[key] = clamped
    setWeights(draft)
  }

  const tabs = [['rules', SlidersHorizontal, 'Rules'], ['challenge', Target, 'Challenge'], ['board', Trophy, 'Board'], ['care', HeartPulse, 'Care']] as const
  return <section aria-labelledby="competition-console-title"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="label-caps text-accent">Momentum · Preview</p><h2 id="competition-console-title" className="mt-1 text-2xl font-semibold tracking-[-0.04em] text-fg">Healthy competition is a team setting.</h2><p className="mt-1 max-w-2xl text-sm leading-relaxed text-fg-muted">Transparent points, restrained recognition, a private path to a better day, and recovery controls that are visible by design.</p></div><span className="rounded-pill border border-success/25 bg-success-subtle px-3 py-2 text-2xs font-semibold text-success"><ShieldCheck aria-hidden size={13} className="mr-1 inline" />Manager controlled</span></header><div className="mt-4 flex gap-1 overflow-x-auto rounded-xl border border-border bg-surface-sunk p-1" role="tablist" aria-label="Momentum console">{tabs.map(([key, Icon, label]) => <button key={key} role="tab" aria-selected={tab === key} onClick={() => setTab(key)} className={['flex min-h-10 min-w-28 flex-1 items-center justify-center gap-1.5 rounded-lg px-3 text-xs font-semibold', tab === key ? 'bg-surface text-fg shadow-elev-1' : 'text-fg-muted hover:text-fg'].join(' ')}><Icon aria-hidden size={14} />{label}</button>)}</div>

    {tab === 'rules' && <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,.85fr)]"><div className="space-y-4"><section className="rounded-xl border border-border bg-surface p-4 shadow-elev-1"><p className="label-caps">Visibility</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><ConfigButton value="full_board" current={visibility} label="Full board" onSelect={setVisibility} /><ConfigButton value="top_three" current={visibility} label="Top-3 only" onSelect={setVisibility} /><ConfigButton value="private" current={visibility} label="Private" onSelect={setVisibility} /></div><p className="mt-3 text-xs text-fg-muted">{VISIBILITY_COPY[visibility]}</p></section>
      <section className="rounded-xl border border-border bg-surface p-4 shadow-elev-1"><div className="flex items-center justify-between"><div><p className="label-caps">Scoring weights</p><h3 className="mt-1 text-sm font-semibold text-fg">Every slider keeps the total at 100%.</h3></div><span className="tnum rounded-pill bg-success-subtle px-3 py-1.5 text-xs font-semibold text-success">{Object.values(weights).reduce((a, b) => a + b, 0)}% locked</span></div><div className="mt-4 space-y-4">{(Object.keys(weights) as ScoreSourceKeyPreview[]).map((key) => <label key={key} className="block"><span className="flex items-center justify-between text-xs"><span className="font-semibold text-fg">{SOURCE_LABEL[key]}</span><strong className="tnum text-fg">{weights[key]}%</strong></span><input type="range" min="5" max="70" value={weights[key]} onChange={(event) => updateWeight(key, Number(event.target.value))} className="mt-2 w-full accent-[var(--accent)]" /><span className="mt-1 block text-2xs text-fg-muted">{key === 'behaviors' ? 'Daily-capped work within a rep’s control.' : key === 'outcomes' ? 'Closed deals and revenue.' : key === 'improvement' ? 'Progress against each rep’s own baseline.' : 'Shared contribution to the agreed team target.'}</span></label>)}</div></section>
      <section className="rounded-xl border border-border bg-surface p-4 shadow-elev-1"><div className="grid gap-4 sm:grid-cols-2"><div><p className="label-caps">Sprint length</p><div className="mt-3 flex flex-wrap gap-2"><ConfigButton value="weekly" current={sprint} label="Weekly" onSelect={setSprint} /><ConfigButton value="biweekly" current={sprint} label="Biweekly" onSelect={setSprint} /><ConfigButton value="monthly" current={sprint} label="Monthly" onSelect={setSprint} /></div><p className="mt-2 text-2xs text-fg-muted">Scores reset on a {sprint} cadence; history and badges remain.</p></div><div><p className="label-caps">Work-hours window</p><div className="mt-3 flex items-center gap-2"><input type="time" value={start} onChange={(event) => setStart(event.target.value)} aria-label="Workday start" className="h-10 min-w-0 flex-1 rounded-md border border-border bg-surface-raised px-2 text-xs text-fg" /><span className="text-fg-subtle">–</span><input type="time" value={end} onChange={(event) => setEnd(event.target.value)} aria-label="Workday end" className="h-10 min-w-0 flex-1 rounded-md border border-border bg-surface-raised px-2 text-xs text-fg" /></div><p className="mt-2 text-2xs text-fg-muted">Outside this window, positions and countdowns disappear; streaks are protected.</p></div></div></section></div>
      <aside><div className="mb-3 flex items-center justify-between"><div><p className="label-caps">Rep preview</p><p className="mt-1 text-xs text-fg-muted">Exactly what this policy reveals.</p></div><button onClick={() => setQuietPreview((value) => !value)} aria-pressed={quietPreview} className="inline-flex min-h-9 items-center gap-1.5 rounded-md border border-border px-3 text-2xs font-semibold text-fg-muted"><Clock3 aria-hidden size={13} />{quietPreview ? 'Show work hours' : 'Preview quiet hours'}</button></div><MomentumCard visibility={visibility} quietHours={quietPreview} /><div className="mt-3 rounded-xl border border-dashed border-border-strong p-3 text-2xs leading-relaxed text-fg-muted"><strong className="text-fg">Consequence:</strong> {VISIBILITY_COPY[visibility]} {start}–{end} is the only competitive window.</div></aside></div>}
    {tab === 'challenge' && <div className="mt-4"><ChallengeComposer visibility={visibility} /></div>}
    {tab === 'board' && <div className="mt-4"><CompetitionBoard /></div>}
    {tab === 'care' && <div className="mt-4"><BurnoutPanel /></div>}
    <p className="mt-4 flex items-center gap-1.5 text-2xs text-fg-subtle"><Users aria-hidden size={12} />Preview — not wired. Reps never receive more comparison than the saved team policy permits.</p>
  </section>
}
