import { useState } from 'react'
import { ArrowUpRight, Award, CalendarDays, Camera, Flame, Lock, Target, TrendingUp, Trophy } from 'lucide-react'
import { EmptyState } from '../../ui/EmptyState'
import { ErrorState } from '../../ui/ErrorState'
import { Skeleton } from '../../ui/Skeleton'
import { ACTIVE_CHALLENGE, BADGES } from './momentumMocks'
import type { VisibilityModePreview } from './momentumMocks'
import { DealWonMoment, MoodPulse } from './RepMomentum'
import { ScoreExplainer } from './ScoreExplainer'

function SeasonSparkline() {
  const values = [720, 805, 780, 940, 1010, 1165, 1285]
  const max = Math.max(...values)
  const min = Math.min(...values)
  const points = values.map((value, index) => `${18 + index * 46},${96 - ((value - min) / (max - min)) * 62}`).join(' ')
  return <svg viewBox="0 0 320 118" className="h-auto w-full" role="img" aria-label="Sprint points improved from 720 to 1,285 over seven sprints"><defs><linearGradient id="season-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--accent)" stopOpacity=".22" /><stop offset="1" stopColor="var(--accent)" stopOpacity="0" /></linearGradient></defs><path d={`M ${points.split(' ').join(' L ')} L 294 108 L 18 108 Z`} fill="url(#season-fill)" /><polyline points={points} fill="none" stroke="var(--accent)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><line x1="18" y1="71" x2="294" y2="71" stroke="var(--border-strong)" strokeDasharray="4 5" /><text x="20" y="67" fill="var(--fg-subtle)" fontSize="9">baseline</text>{values.map((value, index) => <circle key={value} cx={18 + index * 46} cy={96 - ((value - min) / (max - min)) * 62} r={index === values.length - 1 ? 5 : 3} fill={index === values.length - 1 ? 'var(--accent)' : 'var(--surface)'} stroke="var(--accent)" />)}</svg>
}

export function ChallengeCard({ visibility = 'full_board', quietHours = false }: { visibility?: VisibilityModePreview; quietHours?: boolean }) {
  const progress = 24
  return <article className="overflow-hidden rounded-xl border border-border bg-surface shadow-elev-2"><div className="p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-accent-subtle text-accent"><Target aria-hidden size={18} /></span><div className="min-w-0 flex-1"><p className="label-caps text-accent">Active challenge · Preview</p><h3 className="mt-1 text-md font-semibold tracking-[-0.02em] text-fg">{ACTIVE_CHALLENGE.name}</h3><p className="mt-1 text-xs text-fg-muted">Build a week you would want to repeat.</p></div>{!quietHours && <span className="shrink-0 rounded-pill border border-border px-2 py-1 text-2xs font-semibold text-fg-muted">2d 6h left</span>}</div><div className="mt-4 flex items-end justify-between gap-3"><span><strong className="tnum text-2xl text-fg">{progress}</strong><span className="text-xs text-fg-muted"> / {ACTIVE_CHALLENGE.target} follow-ups</span></span><span className="text-right text-2xs font-semibold text-success">{visibility === 'full_board' ? 'Leader: 27' : visibility === 'top_three' ? 'Top pace: 27' : '8 from your target'}</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-pill bg-surface-sunk" role="progressbar" aria-label="Challenge progress" aria-valuemin={0} aria-valuemax={ACTIVE_CHALLENGE.target} aria-valuenow={progress}><div className="h-full rounded-pill bg-accent" style={{ width: `${(progress / ACTIVE_CHALLENGE.target) * 100}%` }} /></div>{quietHours && <p className="mt-3 text-xs text-fg-muted">Progress is safe. The countdown returns with work hours.</p>}</div>{ACTIVE_CHALLENGE.prize && <div className="grid grid-cols-[92px_1fr] border-t border-border bg-surface-sunk"><div role="img" aria-label="Sample prize photograph placeholder: a sunlit team lunch table" className="relative overflow-hidden bg-[linear-gradient(145deg,#d6b989,#6d876f)]"><span aria-hidden className="absolute right-2 bottom-2 h-12 w-16 rounded-[50%] border border-white/40 bg-white/20 shadow-lg" /><Camera aria-hidden size={15} className="absolute top-2 left-2 text-white/80" /></div><div className="p-3"><p className="label-caps">Optional prize</p><p className="mt-1 text-xs font-semibold text-fg">{ACTIVE_CHALLENGE.prize.title}</p><p className="mt-1 text-2xs leading-relaxed text-fg-muted">{ACTIVE_CHALLENGE.prize.caption}</p></div></div>}</article>
}

export default function MySeason({ previewState = 'ready' }: { previewState?: 'ready' | 'loading' | 'empty' | 'error' }) {
  const [scoreOpen, setScoreOpen] = useState(false)
  if (previewState === 'loading') return <div className="space-y-3"><Skeleton className="h-28" /><Skeleton className="h-56" /><Skeleton className="h-40" /></div>
  if (previewState === 'empty') return <EmptyState icon={Trophy} title="Your first season starts today." body="Complete one useful action and your personal baseline will begin—no public comparison is needed." />
  if (previewState === 'error') return <ErrorState title="Couldn’t load your season" body="Your work is safe. Try again when the connection is back." onRetry={() => undefined} />

  return <div className="space-y-4"><section className="overflow-hidden rounded-xl border border-border bg-[linear-gradient(145deg,var(--surface-raised),var(--accent-subtle))] p-5 shadow-elev-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="label-caps text-accent">My season · Preview</p><h2 className="mt-1 text-2xl font-semibold tracking-[-0.04em] text-fg">Built on your own baseline.</h2><p className="mt-2 max-w-sm text-xs leading-relaxed text-fg-muted">Recognition for consistent craft, useful improvement and outcomes—without a public bottom half.</p></div><div className="flex flex-col items-end gap-2"><button onClick={() => setScoreOpen(true)} className="rounded-lg border border-border bg-surface px-3 py-2 text-right shadow-elev-1" aria-label="Explain 1,285 season points"><strong className="tnum block text-xl text-fg">1,285</strong><span className="text-2xs font-semibold text-fg-muted">sprint points · explain</span></button><DealWonMoment /></div></div></section>

    <section><div className="mb-3 flex items-end justify-between"><div><p className="label-caps">Personal bests</p><h3 className="mt-1 text-md font-semibold text-fg">Your wall, not a leaderboard.</h3></div><CalendarDays aria-hidden size={18} className="text-fg-subtle" /></div><div className="grid grid-cols-3 gap-2">{[['11', 'calls in a day'], ['9m', 'median reply'], ['₹2.4L', 'single close']].map(([value, label]) => <div key={label} className="rounded-xl border border-border bg-surface p-3 shadow-elev-1"><strong className="tnum block text-lg text-fg">{value}</strong><span className="mt-1 block text-2xs leading-relaxed text-fg-muted">{label}</span></div>)}</div></section>

    <section className="rounded-xl border border-border bg-surface p-4 shadow-elev-1"><div className="flex items-center justify-between"><div><p className="label-caps">Improvement trend</p><h3 className="mt-1 text-sm font-semibold text-fg">Seven sprints, one steadier curve.</h3></div><span className="flex items-center gap-1 text-xs font-semibold text-success"><ArrowUpRight aria-hidden size={14} />18% vs baseline</span></div><div className="mt-3"><SeasonSparkline /></div><p className="mt-1 flex items-center gap-1.5 text-2xs text-fg-muted"><TrendingUp aria-hidden size={12} />Your baseline moves gradually, so one exceptional week never becomes a permanent burden.</p></section>

    <section><div className="mb-3"><p className="label-caps">Badge shelf</p><h3 className="mt-1 text-md font-semibold text-fg">Earned through work worth repeating.</h3></div><div className="grid grid-cols-2 gap-2">{BADGES.map((badge) => { const earned = !!badge.earnedAt; return <article key={badge.id} className={['rounded-xl border p-4', earned ? 'border-success/25 bg-surface shadow-elev-1' : 'border-border bg-surface-sunk grayscale'].join(' ')}><span className={['flex h-10 w-10 items-center justify-center rounded-xl', earned ? 'bg-success-subtle text-success' : 'bg-surface text-fg-subtle'].join(' ')}>{earned ? <Award aria-hidden size={19} /> : <Lock aria-hidden size={17} />}</span><h4 className="mt-3 text-xs font-semibold text-fg">{badge.name}</h4><p className="mt-1 text-2xs leading-relaxed text-fg-muted">{badge.description}</p><p className="mt-2 text-2xs font-semibold text-fg-subtle">{earned ? 'Earned this season' : 'Locked preview'}</p></article> })}</div></section>

    <ChallengeCard />
    <MoodPulse />
    <ScoreExplainer open={scoreOpen} onClose={() => setScoreOpen(false)} />
    <p className="flex items-center gap-1.5 text-2xs text-fg-subtle"><Flame aria-hidden size={12} />Healthy competition is controlled by your manager’s team settings.</p>
  </div>
}
