import { useEffect, useState } from 'react'
import { Check, CircleHelp, Flame, Moon, PartyPopper, ShieldCheck, Snowflake, Trophy, X } from 'lucide-react'
import { Button } from '../../ui/Button'
import { Sheet } from '../../ui/Sheet'
import { ScoreExplainer } from './ScoreExplainer'
import type { VisibilityModePreview } from './momentumMocks'
import { STREAK_PROTECTION } from './momentumMocks'

export function MomentumCard({ visibility = 'full_board', quietHours = false }: { visibility?: VisibilityModePreview; quietHours?: boolean }) {
  const [explainOpen, setExplainOpen] = useState(false)
  const [freezeOpen, setFreezeOpen] = useState(false)
  const [freezes, setFreezes] = useState(STREAK_PROTECTION.manualTokensRemaining)
  const [protectedStreak, setProtectedStreak] = useState(false)

  if (quietHours) return <section className="overflow-hidden rounded-xl border border-border bg-[linear-gradient(145deg,var(--surface),var(--surface-sunk))] shadow-elev-1"><div className="flex items-start gap-3 p-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-surface-raised text-fg-muted shadow-elev-1"><Moon aria-hidden size={19} /></span><div><p className="label-caps">Quiet hours · Preview</p><h2 className="mt-1 text-lg font-semibold tracking-[-0.025em] text-fg">See you tomorrow.</h2><p className="mt-1 text-xs leading-relaxed text-fg-muted">Positions, gaps and challenge countdowns rest outside 9:00 am–6:30 pm.</p></div></div><div className="flex items-center gap-2 border-t border-border px-4 py-3 text-xs font-semibold text-success"><ShieldCheck aria-hidden size={14} /> Your streak is protected automatically.</div></section>

  return <>
    <section className="overflow-hidden rounded-xl border border-[color-mix(in_srgb,var(--accent)_20%,var(--border))] bg-[linear-gradient(150deg,var(--surface-raised),var(--accent-subtle))] shadow-elev-2" aria-labelledby="momentum-card-title">
      <div className="p-4"><div className="flex items-start gap-4"><div className="min-w-0 flex-1"><p className="label-caps text-accent">Sprint momentum · Preview</p><h2 id="momentum-card-title" className="mt-1 text-lg font-semibold tracking-[-0.025em] text-fg">A strong day is still yours.</h2></div><button onClick={() => setExplainOpen(true)} className="rounded-lg border border-border bg-surface px-3 py-2 text-right shadow-elev-1" aria-label="1,285 points. Explain how points work"><strong className="tnum block text-lg leading-none text-fg">1,285</strong><span className="mt-1 flex items-center gap-1 text-2xs font-semibold text-fg-muted">points <CircleHelp aria-hidden size={11} /></span></button></div>
        <div className="mt-4 rounded-lg border border-border bg-surface/80 p-3">
          {visibility === 'full_board' && <><p className="text-sm font-semibold text-fg">#4 of 9 <span className="font-normal text-fg-muted">· ₹30k behind #3</span></p><p className="mt-1 text-xs text-fg-muted">Two on-time follow-ups move you toward the next rung.</p></>}
          {visibility === 'top_three' && <><div className="flex flex-wrap gap-1.5"><span className="rounded-pill bg-surface-sunk px-2 py-1 text-2xs font-semibold text-fg">Priya</span><span className="rounded-pill bg-surface-sunk px-2 py-1 text-2xs font-semibold text-fg">Nikhil</span><span className="rounded-pill bg-surface-sunk px-2 py-1 text-2xs font-semibold text-fg">Meera</span></div><p className="mt-2 text-xs font-semibold text-success">You: on pace for your best week.</p></>}
          {visibility === 'private' && <><p className="text-sm font-semibold text-fg">Your best week is 86 points away.</p><p className="mt-1 text-xs text-fg-muted">Today’s follow-up quality is 18% above your baseline.</p></>}
        </div>
      </div>
      <button onClick={() => setFreezeOpen(true)} className="flex min-h-12 w-full items-center gap-2 border-t border-border bg-surface/70 px-4 text-left text-xs font-semibold text-fg hover:bg-surface"><span className={['flex h-8 w-8 items-center justify-center rounded-lg', protectedStreak ? 'bg-info-subtle text-info' : 'bg-warn-subtle text-warn'].join(' ')}>{protectedStreak ? <Snowflake aria-hidden size={15} /> : <Flame aria-hidden size={15} />}</span><span className="min-w-0 flex-1">{protectedStreak ? 'Streak protected today' : '6-day consistency streak'}</span><span className="text-fg-muted">{freezes} freezes left</span></button>
    </section>
    <ScoreExplainer open={explainOpen} onClose={() => setExplainOpen(false)} />
    <Sheet open={freezeOpen} onClose={() => setFreezeOpen(false)} title="Protect today’s streak?">
      <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-info-subtle text-info"><Snowflake aria-hidden size={21} /></span><h3 className="mt-4 text-xl font-semibold tracking-[-0.03em] text-fg">Rest without losing the rhythm.</h3><p className="mt-2 text-sm leading-relaxed text-fg-muted">Leave, weekends and company holidays are protected automatically. A manual freeze uses one of your {freezes} monthly tokens.</p><div className="mt-5 rounded-lg bg-surface-sunk p-3 text-xs text-fg-muted"><strong className="text-fg">Nothing else changes.</strong> Your score, position and next action stay as they are.</div><Button size="lg" className="mt-5 w-full" disabled={freezes === 0 || protectedStreak} onClick={() => { setFreezes((value) => Math.max(0, value - 1)); setProtectedStreak(true); setFreezeOpen(false) }}>{protectedStreak ? 'Already protected' : 'Use one freeze'}</Button><button onClick={() => setFreezeOpen(false)} className="mt-2 min-h-10 w-full text-xs font-semibold text-fg-muted">Keep streak active</button><p className="mt-2 text-center text-2xs text-fg-subtle">Preview — no token is spent</p>
    </Sheet>
  </>
}

export function MoodPulse() {
  const [choice, setChoice] = useState<'heavy' | 'steady' | 'good' | null>(null)
  const [hidden, setHidden] = useState(false)
  if (hidden) return null
  return <section className="rounded-xl border border-border bg-surface p-4 shadow-elev-1" aria-labelledby="mood-title"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="label-caps text-accent">Optional weekly pulse · Preview</p><h2 id="mood-title" className="mt-1 text-sm font-semibold text-fg">How was your week?</h2><p className="mt-1 text-2xs leading-relaxed text-fg-muted">Private to the aggregate. Managers see only the team trend—never your answer.</p></div><button onClick={() => setHidden(true)} aria-label="Dismiss mood pulse forever" className="rounded-md p-1.5 text-fg-subtle hover:bg-surface-sunk hover:text-fg"><X aria-hidden size={15} /></button></div><div className="mt-3 grid grid-cols-3 gap-2">{([['heavy', '◡', 'Heavy'], ['steady', '—', 'Steady'], ['good', '⌒', 'Good']] as const).map(([key, face, label]) => <button key={key} onClick={() => setChoice(key)} aria-pressed={choice === key} className={['min-h-14 rounded-lg border text-center', choice === key ? 'border-accent bg-accent-subtle text-accent' : 'border-border bg-surface-raised text-fg-muted'].join(' ')}><span className="block text-lg leading-none">{face}</span><span className="mt-1 block text-2xs font-semibold">{label}</span></button>)}</div>{choice && <p className="mt-3 flex items-center gap-1.5 text-2xs font-semibold text-success" role="status"><Check aria-hidden size={12} /> Thanks. Included only in the anonymous team trend preview.</p>}</section>
}

export function DealWonMoment() {
  const [open, setOpen] = useState(false)
  useEffect(() => { if (!open) return; const timer = window.setTimeout(() => setOpen(false), 1900); return () => window.clearTimeout(timer) }, [open])
  return <><button onClick={() => setOpen(true)} className="inline-flex min-h-9 items-center gap-1.5 rounded-md border border-border px-3 text-xs font-semibold text-fg-muted hover:bg-surface-sunk"><Trophy aria-hidden size={14} /> Preview win moment</button>{open && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[var(--overlay)] p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Deal won celebration"><span aria-hidden className="absolute h-72 w-72 animate-ping rounded-full border border-success/20 motion-reduce:animate-none" /><div className="relative w-full max-w-md overflow-hidden rounded-2xl border border-success/25 bg-surface p-7 text-center shadow-elev-3"><button onClick={() => setOpen(false)} aria-label="Close celebration" className="absolute top-3 right-3 rounded-md p-2 text-fg-subtle hover:bg-surface-sunk"><X aria-hidden size={16} /></button><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-success-subtle text-success"><PartyPopper aria-hidden size={24} /></span><p className="label-caps mt-5 text-success">Deal won · Preview</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.05em] text-fg">₹2.4L closed.</h2><p className="mt-2 text-sm text-fg-muted">Mumbai Clinic · your sprint total is now 1,285.</p><div className="mx-auto mt-5 inline-flex items-center gap-2 rounded-pill border border-border bg-surface-sunk px-3 py-2 text-xs font-semibold text-fg"><Trophy aria-hidden size={14} className="text-success" /> Promise keeper earned</div><p className="mt-5 text-2xs text-fg-subtle">This closes automatically. Reduced motion shows the same static card.</p></div></div>}</>
}
