import { Check, Gauge, ShieldCheck } from 'lucide-react'
import { Sheet } from '../../ui/Sheet'
import { BEHAVIOR_SCORES, SCORE_SOURCES } from './momentumMocks'

export function ScoreExplainer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const total = SCORE_SOURCES.reduce((sum, source) => sum + source.points, 0)
  return <Sheet open={open} onClose={onClose} title="How your points work">
    <div className="flex items-start gap-3 rounded-xl border border-border bg-surface-sunk p-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-accent-subtle text-accent"><Gauge aria-hidden size={18} /></span><div><p className="label-caps text-accent">Your sprint · Preview</p><p className="mt-1 text-2xl font-semibold tracking-[-0.035em] text-fg"><span className="tnum">{total.toLocaleString('en-IN')}</span> points</p><p className="mt-1 text-xs leading-relaxed text-fg-muted">The score rewards useful work, real outcomes, progress against your own baseline and contribution to the team.</p></div></div>
    <div className="mt-5 space-y-4">{SCORE_SOURCES.map((source) => <section key={source.key}><div className="flex items-baseline gap-3"><h3 className="min-w-0 flex-1 text-sm font-semibold text-fg">{source.label} <span className="font-normal text-fg-subtle">· {source.weight}%</span></h3><strong className="tnum text-sm text-fg">{source.points}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-pill bg-surface-sunk"><div className="h-full rounded-pill bg-accent" style={{ width: `${(source.points / total) * 100}%` }} /></div><p className="mt-2 text-xs leading-relaxed text-fg-muted">{source.explanation}</p></section>)}</div>
    <section className="mt-6 border-t border-border pt-5"><div className="flex items-center justify-between"><div><p className="label-caps">Behavior detail</p><h3 className="mt-1 text-sm font-semibold text-fg">Daily caps keep the system honest.</h3></div><ShieldCheck aria-hidden size={18} className="text-success" /></div><div className="mt-3 divide-y divide-border overflow-hidden rounded-xl border border-border bg-surface">{BEHAVIOR_SCORES.map((behavior) => <div key={behavior.label} className="flex items-center gap-3 px-3 py-3"><span className={['flex h-7 w-7 shrink-0 items-center justify-center rounded-md', behavior.capped ? 'bg-success-subtle text-success' : 'bg-surface-sunk text-fg-muted'].join(' ')}>{behavior.capped ? <Check aria-hidden size={13} /> : <span className="tnum text-2xs">+{Math.min(behavior.points, 9)}</span>}</span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold text-fg">{behavior.label}</span><span className="mt-0.5 block text-2xs text-fg-muted">{behavior.points} this sprint · daily cap {behavior.dailyCap}</span></span>{behavior.capped && <span className="rounded-pill border border-success/25 bg-success-subtle px-2 py-1 text-2xs font-semibold text-success">Maxed today</span>}</div>)}</div></section>
    <p className="mt-4 text-2xs leading-relaxed text-fg-subtle">Preview — scores are sample data. Caps, weights and eligibility become manager-controlled policy when wired.</p>
  </Sheet>
}
